# we create a Docker image from source code
version: '3.8'
services:
  dev-database:
    image: postgres:15.0
    container_name: dev-database
    ports:
      - 5434:5432 #port in host(myPC) : {port in Container}
    #environment variables, like: db's username, password...
    environment:
      POSTGRES_USER: chinkin123
      POSTGRES_PASSWORD: Chinkin@123
      POSTGRES_DB: nestjs
    networks:
      - nestjs-network
networks:
  nestjs-network: